# Generated by Django 5.2.5 on 2025-08-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ice_cream", "0002_alter_category_options_alter_icecream_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="icecream",
            name="output_order",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Порядок вывода"
            ),
        ),
        migrations.AddField(
            model_name="icecream",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                help_text="Уникальное название обёртки, не более 256 символов",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="icecream",
            name="title",
            field=models.CharField(
                help_text="Уникальное название мороженого, не более 256 символов",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="topping",
            name="title",
            field=models.CharField(
                help_text="Уникальное название топпинга, не более 256 символов",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="wrapper",
            name="title",
            field=models.CharField(
                help_text="Уникальное название обёртки, не более 256 символов",
                max_length=256,
                verbose_name="Название",
            ),
        ),
    ]
