# Generated by Django 5.2.5 on 2025-08-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ice_cream", "0003_icecream_output_order_icecream_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="icecream",
            options={
                "ordering": ("output_order", "title"),
                "verbose_name": "мороженое",
                "verbose_name_plural": "Мороженое",
            },
        ),
    ]
